

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
gems: ["jekyll-paginate", "pygments.rb", "redcarpet"]

# Help Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Wilson Zhao 
tagline:          'Student, Programmer, Hackathon Attendee, CMU Class of 2019'
description:      'Programmer, Hackathon Attendee, CMU Class of 2019'
url:              hyde.getpoole.com
baseurl:          / 

author:
  name:           'Wilson Zhao'
  url:            https://twitter.com/mdo
  

paginate:         5

# Custom vars
version:          2.1.0


resume:
  link:           http://www.wilsonzhao.com/img/Wilson_Zhao_Resume.pdf
github:
  link:		      https://github.com/wilzh40
  repo:           https://github.com/poole/hyde

