

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

# Help Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Wilson Zhao 
tagline:          'Student, Programmer, Hackathon Attendee, CMU Class of 2019'
description:      'Programmer, Hackathon Attendee, CMU Class of 2019'
url:              hyde.getpoole.com
baseurl:          /

author:
  name:           'Wilson Zhao'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0


resume:
  link:           http://registry.jsonresume.org/wilzh40
github:
  link:		      https://github.com/wilzh40
  repo:           https://github.com/poole/hyde
